### PR TITLE
PAT: support promises in GetOpenTables and BillPaymentFlowEnded

### PR DESCRIPTION
**Pull request by omeid**
This commit adds support for promises in GetOpenTables and BillPaymentFlowEnded to allow better integration with Table Servers.

### CODE REVIEW

**Review by mattgresham — APPROVED** [review]

**Comment by mattgresham** [comment]
Alax confirmed that there are no POSes using the JS library and P@T so all good.

What do you both think about merging this into a 2.9.1 "release" branch and getting any other changes required out after the 2.9.0 changes that are in progress at the moment?

**Comment by omeid** [comment]
I am happy either way, we can use a specific branch for Spice with these commits in the meantime. I will try to fix this once I am ready to push Spice P@T work.

**Comment by omeid** [comment]
@mattgresham Where would you like this merged?

**Comment by mattgresham** [comment]
> @mattgresham Where would you like this merged?

How about a `feature/2.9.1` branch and when no other changes are needed, we can just bump the library version and release all the changes? That way we can keep all the library changes/versions in sync and reduce the load on QA for the moment

**Comment by omeid** [comment]
@mattgresham Sure, ready to merge.

**Pull request merged**
